spring:
  security:
    oauth2:
      client:
        registration:
          b2c-github:
            provider: b2c-github-provider
            client-id: 67e84c97-97a2-4c62-8a6c-4db3e16c8536
            client-secret: Rz.-YMH00.pBV60bS-4BkJsU577wMU~txw
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: openid
        provider:
          b2c-github-provider:
            authorization-uri: https://jsblogs.b2clogin.com/jsblogs.onmicrosoft.com/b2c_1_jsblogs_github/oauth2/v2.0/authorize
            token-uri: https://jsblogs.b2clogin.com/jsblogs.onmicrosoft.com/b2c_1_jsblogs_github/oauth2/v2.0/token
            jwk-set-uri: https://jsblogs.b2clogin.com/jsblogs.onmicrosoft.com/b2c_1_jsblogs_github/discovery/v2.0/keys
server:
  forward-headers-strategy: native
